name: Build and deploy the website

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install npm git
          npm install -g npm

      - name: Clone the repo
        run: |
          cd /
          sudo git clone https://github.com/LLK/scratch-www.git
          
      - name: Install npm dependencies
        run: |
          cd /scratch-www
          sudo npm install --force
        
      - name: Build the website
        run: |
          cd /scratch-www
          sudo npm run build
        
      - name: Zip the website
        run: |
          cd /
          sudo mkdir output
          sudo zip -r /output/scratch-www.zip /scratch-www/build
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main
          files: |
              /output/scratch-www.zip

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: "scratch-www"
          path: "/scratch-www/build"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /scratch-www/build
          publish_branch: gh-pages
